### ISSUE TITLE
Imporove logging

### ISSUE THREAD

**Issue by yurem** [GluuFederation/gluu-passport#1]
W need to improve logging
1) App should use "node.logging.dir" param if it exists to specify right place of logs
2) We need to rename logs.log to passport.log
3) We need to add new log "stderrout.log" to log into it standart console messages
4) Can we do logrotate on daily basis from node?
We need to do lograte:
- passport.log
- stderrout.log

**Comment by arvindsinghtomar** [comment]
1. We have changed the APP param to environment variable NODE_LOGGING_DIR and used it as default logging dir.
2. Renamed logs.log file to passport.log file.
3. Removed stderrout.log as it was just for testing.
4. Added logrotate for passport.log on daily basis.
