### ISSUE TITLE
Readability of passport log

### ISSUE THREAD

**Issue by mzico** [GluuFederation/gluu-passport#10]
Passport log is really hard to read.. we should implement some newline, indentation or w/e is required to make it easier. 

Here is how it looks like now: 

![screenshot_3](https://user-images.githubusercontent.com/7156097/34883855-81cf4af8-f780-11e7-86e6-7cfffe3e3393.png)

**Comment by yurem** [comment]
I added own formatter which I think should help. Can you check [new passport](https://ox.gluu.org/npm/passport/passport-3.1.3.tgz) with 3.1.3 beta1?
