### ISSUE TITLE
Apply js-standard code guidelines on eslint

### ISSUE THREAD

**Issue by christian-hawk** [GluuFederation/gluu-passport#109]
Currently we are not using a standard.
Between the options, https://standardjs.com/ is the most advanced and no bureaucracy.

**Comment by christian-hawk** [comment]
suggestion: use eslint to extend standardjs

**Comment by kdhttps** [comment]
> suggestion: use eslint to extend standardjs

@christian-hawk not getting you exactly. there are two ways to integrate `standardjs`. 
1. directly with standard npm as describe in standard docs.
2. using eslint `npx eslint --init` which is also install some eslint libs

so do you want me to use 2nd one?

**Comment by christian-hawk** [comment]
@kdhttps I understand that for CI/CD purposes standard npm should work.
But maybe **eslint** is more globally known and integrated on IDE and Text Editors, this is why I thought using standard as a plugin. What do you think?

I'm ok w/ any option thou.

**Comment by kdhttps** [comment]
I think let's use `standardjs`. it is used by well know companies and only one lib for everything without any extra configuration. @christian-hawk what you think?

**Comment by christian-hawk** [comment]
Agreed.
