### ISSUE TITLE
Passport should return non zero exit code on startup errors

### ISSUE THREAD

**Issue by yurem** [GluuFederation/gluu-passport#11]
When passport start fail due to error like:
```
2018-04-10T04:30:30+0000 [INFO] UMAConfigurations were received
2018-04-10T04:30:30+0000 [ERROR] Error in starting the server. error:-  https://u144.gluu.info/oxauth/restv1/token
```
It should return no zero exit code to notify startup script

**Comment by jgomer2001** [comment]
According to the timer added in #12, the service is always running (always doing attempts to obtain the configuration), so it does not report any startup errors.

**Comment by natt-tester** [comment]
Tested in 3.1.4 + Ubuntu 3.1.4 + Firefox. I think it still needs improvement -- the error code command shows 0 after restarting passport, but the logs show one repeated error:

<img width="774" alt="starting_passport" src="https://user-images.githubusercontent.com/38302725/44140350-2adadb86-a0bd-11e8-94f5-7c045cd6287c.png">
<img width="656" alt="passport_error" src="https://user-images.githubusercontent.com/38302725/44140419-5d5493cc-a0bd-11e8-92d2-95375e6883c0.png">
