### ISSUE TITLE
Add endpoints to track steps taken in the passport flow. 

### ISSUE THREAD

**Issue by moabu** [GluuFederation/gluu-passport#110]
As a **Site Reliability Engineer**
Want to **easily pickup on endpoint fails**
So I can **keep the service up** and **respond faster**.

Using open metrics [standards](https://github.com/OpenObservability/OpenMetrics) we need to identify and expose passport flow endpoints. Similar in oxAuth , in the authorization flow we could track endpoints like `/token`, `/authorize`, `/oxauth/login`.

**Comment by christian-hawk** [comment]
As a **Site Reliability Engineer**
Want to **easily pickup on endpoint fails**
So I can **keep the service up** and **respond faster**.
