### ISSUE TITLE
Re-attempt to get oxAuth metadata and token

### ISSUE THREAD

**Issue by yurem** [GluuFederation/gluu-passport#12]
For better user experience passport should re-try initialization on request.

Now it do this at startup. As result service fails and admin should restart it manually after enabling passport in GUI.

**Comment by afroDC** [comment]
@yurem How would you like to see this re-try initialization on request process work?

**Comment by yurem** [comment]
This app gets configuration from oxTrust. But it also requires oxAuth because this endpoint protected by UMA. Hence Passprot in some case can't get it configuration. As result it just print error in log.

Passprot app should try to get configuration at startup and store `load_configuration_state` (now it just print error). On next request to app context it should check `load_configuration_state` and try to obtain configuration again.

Also it will be useful to add timer process to get up to date configuration from oxTrust periodically to avoid Passport restart.

**Comment by jgomer2001** [comment]
implementing timer and refactoring around `auth\getConsumerDetails.js`
