### ISSUE TITLE
New Feature: Add private_key_jwt token endpoint auth method support in inbound passport oidc

### ISSUE THREAD

**Issue by kdhttps** [GluuFederation/gluu-passport#123]
Currently, our passport module is using `passport-openiconnect` npm package which uses `oauth` npm package which only supports `client_secret_post`.

### Expected behavior
Inbound passport should support every token endpoint auth method.
1. `client_secret_basic`
2. `client_secret_post`
3. `private_key_jwt`
4. `none` - PKCE flow

### Actual behavior
passport module failed to get token when external OP provider has `private_key_jwt` token endpoint auth method.

Support request https://support.gluu.org/authentication/9003/external-openid-connect-provider-using-private_key_jwt-as-token-endpoint-auth-method/

I think for this we need to make our own new OIDC passport strategy. @christian-hawk and @jgomer2001 please provide your suggestion on this.

**Comment by kdhttps** [comment]
http://www.passportjs.org/packages/openid-client/

This may help us.

**Comment by jgomer2001** [comment]
Yes, I made my own attempt in the past and failed: https://github.com/GluuFederation/gluu-passport/issues/78

Also one of the big challenges of the integration is that such lib does not  follow the same "structure" of most (all?) existing passport strategies, thus introducing certain friction

By using oxd (which is already OIDC full-featured & battle-tested)  plus registering the provider with type="openidconnect-oxd"  (as suggested in the ticket) we can cover many of the use cases

**Comment by kdhttps** [comment]
Ok Agree, but we still need to update `passport-oxd` strategy as I can see in code it is only supporting `client_secret_basic` token auth method
https://github.com/GluuFederation/passport-oxd/blob/master/lib/strategy.js#L106
https://github.com/GluuFederation/passport-oxd/blob/master/lib/utils.js#L69

**Comment by jgomer2001** [comment]
I don't think so. passport-oxd "talks" to OXD using a specific [API](https://www.gluu.org/docs/oxd/api/) exposed by it. passport-oxd never interacts with the OP directly, it uses OXD server as middle-man.

If you can manage some time, check OXD documentation and try to setup an environment and test the use case. In practice we only have tested very basic configs when using passport-oxd, so this will help us to know  how well we are covered.

**Comment by kdhttps** [comment]
I got your point that OXD is middleware and it can do anything but it will only work properly when we request it with valid and proper data. Currently, in `passport-oxd` it is hardcoded and only handle the `client_secret_basic` token auth method case. 

If the token endpoint method is `private_key_jwt`, we have to give it some extra request parameters to get the token from `/get-client-token` oxd endpoint e.g. `authentication_method`, `key_id` and `algorithm`. so how can I pass these parameters in `passport-oxd`? There is no configuration in `passport-oxd` strategy.

I checked the `passport-oxd` code, there is no facility to pass or handle the request in `private_key_jwt` token endpoint auth case So I think we have to update the `passport-oxd` code to handle this case.

Please correct me if I am wrong or miss something?

**Comment by christian-hawk** [comment]
> If you can manage some time, check OXD documentation and try to setup an environment and test the use case. In practice we only have tested very basic configs when using passport-oxd, so this will help us to know how well we are covered.

If is possible to have this use-case, can you guys please add this test-case  [`gluu-passport-testing`](https://github.com/GluuFederation/gluu-passport-testing) repo?

Interesting discussion.

**Comment by jgomer2001** [comment]
Thanks for checking @kdhttps . I wasn't aware of this:

>  There is no configuration in passport-oxd strategy.

So that means we are maybe missing lots of scenarios for OIDC authentication? Then, at this point I'm not sure if we should continue growing `passport-oxd` codebase or give `openid-client` a second opportunity :)

**Comment by kdhttps** [comment]
I think, give me some time. I would like to take a look at `openid-client`

**Comment by kdhttps** [comment]
@jgomer2001 @christian-hawk I got the success with `openid-client`. successfully integrated with gluu-passport. we should add this in Gluu 5.0.

**Comment by christian-hawk** [comment]
Great job!

**Comment by kdhttps** [comment]
we will cover this issue in https://github.com/GluuFederation/gluu-passport/issues/206
and
closing this one
