### ISSUE TITLE
Avoid assignments in operand on openid-client-helper

### ISSUE THREAD

**Issue by christian-hawk** [GluuFederation/gluu-passport#150]
#### Currently on:
+ **Commit**:  2f666fc3a3f0e95e50d35a7542a9bab95a846e21
+ **File**:    [server/utils/openid-client-helper.js](https://github.com/GluuFederation/gluu-passport/blob/2f666fc3a3f0e95e50d35a7542a9bab95a846e21/server/utils/openid-client-helper.js)
+ **LineNum**: [118](https://github.com/GluuFederation/gluu-passport/blob/2f666fc3a3f0e95e50d35a7542a9bab95a846e21/server/utils/openid-client-helper.js#L118)

**Comment by kdhttps** [comment]
we removed ` server/utils/openid-client-helper.js` so need to keep this issue, closing
