### ISSUE TITLE
Remove unused openid-client dependency

### ISSUE THREAD

**Issue by kdhttps** [GluuFederation/gluu-passport#165]
Currently we are not using `openid-client` deps so we can remove it from dependencies

**Comment by christian-hawk** [comment]
@kdhttps thx 4 the issue. 

while [searching for `openid-client` on this repo ](https://github.com/GluuFederation/gluu-passport/search?q=openid-client) I found this:
![image](https://user-images.githubusercontent.com/59786962/100229333-d7afe100-2f02-11eb-96a9-0c8871e7d308.png)

could you please double check if it's unused?

Thanks

**Comment by kdhttps** [comment]
Yes, it is unused. Also we can remove file `openid-client-helper.js`
