### ISSUE TITLE
Passing non-user attributes from idp provider to OP (custom_data)

### ISSUE THREAD

**Issue by christian-hawk** [GluuFederation/gluu-passport#187]
Please check https://github.com/GluuFederation/oxAuth/issues/1510

## Story
Me as **a customer**
Want to **be able to override id token lifetime**
So I can **control session timeout**

## Feature
send custom_data to OP (oxAuth)

### Main scenario
```gherkin
Given default id_token lifetime is 1 day
  And IDP is sending a custom id_token lifetime of 3 days
When I authenticate
Then session token lifetime value should be 3 days
```

### Passport Context scenario
```gherkin
Given default id_token lifetime is 60000 ms
   And IDP is sending a custom id_token lifetime of 120000 ms
When passport receives IDP data
  Then passport sends `custom_data` claim on JWT with `internal_override_id_token_lifetime` key with 120000 value.
```

- [ ] implement new jwt claim `custom_data`
- [ ] check for non-user attributes (custom) on idp message
- [ ] send this attributes on `custom_data` to `passport-saml` script.

**Comment by jgomer2001** [comment]
Check https://gluu.org/docs/gluu-server/4.2/tutorials/passport-attributes-mapping/#advanced-sending-more-than-profile-data-to-custom-script

**Comment by christian-hawk** [comment]
- [ ] check if https://github.com/GluuFederation/oxAuth/issues/1523 closes **this** issue

**Comment by kdhttps** [comment]
We don't need to modify any code at passport. Admin can easily use mapping file and pass non-user attributes to OP Server.
For example:
If Admin want to pass `sessionNotOnOrAfter` to OP server then admin can add it in `saml_ldap_profile.js` mapping file like below:
```
module.exports = profile => {
  return {
    uid: profile['urn:oid:0.9.2342.19200300.100.1.1'],
    mail: profile.email || profile['urn:oid:0.9.2342.19200300.100.1.3'] || profile['urn:oid:1.2.840.113549.1.9.1'],
    cn: profile['urn:oid:2.16.840.1.113730.3.1.241'],
    displayName: profile['urn:oid:2.16.840.1.113730.3.1.241'],
    givenName: profile['urn:oid:2.5.4.42'],
    sn: profile['urn:oid:2.5.4.4'],
    sessionNotOnOrAfter: profile.getAssertion().Assertion.AuthnStatement[0].$.SessionNotOnOrAfter
  }
}

```

`passport-saml` strategy returns us SAML Assertion in profile object `profile.getAssertion().Assertion`. Which we can use and pass like above example. Closing Ticket.
