### ISSUE TITLE
Passport should support dynamic mapping

### ISSUE THREAD

**Issue by yurem** [GluuFederation/gluu-passport#19]
Right now passport knows about only hardcoded list of user attributes: https://support.gluu.org/single-sign-on/5354/accessing-memberof-in-sso-environment/#at32535

It should should use `/etc/gluu/conf/passport-saml-config.json` in mapping to allow map any attributes to local user attributes. This mapping should be configurable for each provider. Also we should update mapping to map into Gluu attributes

Also custom script has 2 properties:
```
generic_remote_attributes_list = username, email, name, name, givenName, familyName, provider, memberOf
generic_local_attributes_list = uid, mail, cn, displayName, givenName, sn, provider, memberOf
```
I think if passport returns attributes in convenient for Gluu attributes we can make this mapping optional. By default we can use all attributes from request.

**Comment by jgomer2001** [comment]
Tackling attribute mapping stuff is in our [roadmap](https://github.com/GluuFederation/gluu-passport/wiki/Inbound-indentity-improvements#targeting-40) for 4.0. I think it deserves careful redesign and should cope with both flavors of inbound identity: saml & social.

**Comment by shmorri** [comment]
Documented in this [tutorial](https://gluu.org/docs/ce/4.0/tutorials/passport-attributes-mapping/)
