### ISSUE TITLE
Add Support for MQ logging

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-passport#2]
In a cluster, we use ActiveMQ for logging to send messages to a central logging server. Passport needs to support this.

**Comment by arvindsinghtomar** [comment]
I was going through ActiveMQ logging and have found that we are storing the credentials in LDAP and passport does not communicate to LDAP directly. I have found an npm module which supports ActiveMQ in node. Here is the link: https://www.npmjs.com/package/stomp-client to the module.

**Comment by yurem** [comment]
In oxAuth there is class which we uses to send JMS messages
https://github.com/GluuFederation/oxAuth/blob/master/Server/src/main/java/org/xdi/oxauth/audit/ApplicationAuditLogger.java#L79

We have 2 solutions. Send messages from passport? Or send messages from passport script via oxAuth services.

**Comment by nynymike** [comment]
Send messages from passport...

**Comment by arvindsinghtomar** [comment]
@yurem Can we add the required details for ActiveMQ to passport-config.json file?

**Comment by nynymike** [comment]
Yes, that makes sense. Also remember that ActiveMQ logging is optional. It's only needed for clustered deployments.

**Comment by willow9886** [comment]
@arvindsinghtomar any status update on this? was it included in 3.0 ? or does the milestone need to be updated?

**Comment by nynymike** [comment]
I moved this to 3.1

**Comment by arvindsinghtomar** [comment]
Hi @Will and @Mike,
I have already added ActiveMQ support for passport as an optional feature.
The configurations reterived and checked if the activeMQ feature is enabled or not.
@Yuriym, Did you added the activeMQ configuration settings to change the passport conf file when activeMQ settings are changed?

**Comment by will** [comment]
Is activemq like rabbitmq? I remember getting paged for rabbitmq backlogs the first year I worked at heroku but then we split into smaller teams and I didn't have to deal with that anymore. That is everything I know about MQ things. Sorry I can't be of any more help.

**Comment by yurem** [comment]
@arvindsinghtomar which settings do you mean?
