### ISSUE TITLE
Replace deprecated request module

### ISSUE THREAD

**Issue by kdhttps** [GluuFederation/gluu-passport#204]
The [request](https://github.com/request/request) lib is completely deprecated and with [security risk](https://github.com/jaredhanson/passport-openidconnect/issues/78). We have to replace it with [other libs](https://github.com/request/request/issues/3143).

I would like to suggest and use [got](https://www.npmjs.com/package/got). 

Currently `request` module is used at 2 places

## 1. To fetch passport config [here](https://github.com/GluuFederation/gluu-passport/blob/master/server/utils/uma.js#L1)
I am not finding any difficulties to refactor code and use `got` [here](https://github.com/GluuFederation/gluu-passport/blob/master/server/utils/uma.js#L1).

## 2. Used by [`passport-openidconnect`](https://github.com/jaredhanson/passport-openidconnect/blob/master/package.json#L37) strategy.
we are using this strategy for OIDC passport flow.

### Solution-1
As I can see in `passport-openidconnect` repo [issues#78](https://github.com/jaredhanson/passport-openidconnect/issues/78) about [`request` deprecation](https://github.com/jaredhanson/passport-openidconnect/issues/78), the author is not really giving any attention and no activities on issue so I think we have only one way here. Fork repo `passport-openidconnect`, replace code to remove `request` and use `got` and use our version for `gluu-passport`.

### Solution-2
We can remove `passport-openidconnect` and use [`openid-client`](https://www.npmjs.com/package/openid-client). which is the great lib with more features and I already tested it with `private-key-jwt` token endpoint auth method flow [here gluu-passport/issues/123](https://github.com/GluuFederation/gluu-passport/issues/123#issuecomment-725950883). but I am not sure what it will be impact on customers who are already using `passport-openidconnect`.

IMO, the solution-2 will be the good choice because we can cover more number of OIDC use cases using [`openid-client`](https://www.npmjs.com/package/openid-client) lib.

@christian-hawk, @jgomer2001  and @nynymike what you think about this?

**Comment by jgomer2001** [comment]
I vote No 2 as well. We are about to release 4.2.3 so we se shouldn't touch much of the code now. 4.2.4 would be fine. Regarding customer impact the upgrade procedure should handle it. A detail doc with steps to transform passport-openidconnect -> openid-client must be handed to upgrade developer.

**Comment by christian-hawk** [comment]
We have 2 issues mentioned there, both regarding the same vulnerabilities (most of them critical) and responsible for 250+ security scan warnings.

**I say we split this issue in 2 issues mentioned.**

First we take care of issue 1 (fetching config file, not complex), then issue 2 (replacing old `passport-openidconnect`).

As @jgomer2001 also vote for **Solution 2**, `openid-client` has ben an active repo and is also [OpenID Certified](https://github.com/panva/node-openid-client#certification).

**Comment by kdhttps** [comment]
Thanks Chris and Jose. I'll go with `openid-client` and @christian-hawk sure, I'll split it into 2 issues.

**Comment by kdhttps** [comment]
Create two separate issues
1. Update uma.js to use got lib and remove request https://github.com/GluuFederation/gluu-passport/issues/205
1. Replace `passport-openidconnect` with `openid-client`  https://github.com/GluuFederation/gluu-passport/issues/206

and closing this one
