### ISSUE TITLE
Passport-Saml: IDP initiated flow fail

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/gluu-passport#24]
# Description

After setting up the inbound saml between Gluu and okta. The SP initiated flow works well.
But the IDP is failing.

See logs:
[oxauth.log](https://github.com/GluuFederation/gluu-passport/files/1974038/oxauth.log)
[oxauth_script.log](https://github.com/GluuFederation/gluu-passport/files/1974039/oxauth_script.log)

 for more details.

**Comment by jgomer2001** [comment]
Split into issues listed above

**Comment by yurem** [comment]
https://github.com/GluuFederation/gluu-passport/commit/e2d467acb0bc718df2df77e05cf546ab3e0d6a4a

**Comment by yurem** [comment]
https://github.com/GluuFederation/gluu-passport/commit/656794d9188b1dff58786c4e2cbd913a04c4c438

**Comment by yurem** [comment]
https://github.com/GluuFederation/gluu-passport/commit/1ed4bbecc19209957432820cc69c24f6dd0cd948

**Comment by yurem** [comment]
https://github.com/GluuFederation/community-edition-setup/commit/cac9bbcf8513c53e2ec35d7e18dc7239619b3c98

**Comment by yurem** [comment]
Implemented and customer confirmed that it works well
