### ISSUE TITLE
Log enhancement: declare missing resource ( lack of authN server ) 

### ISSUE THREAD

**Issue by mzico** [GluuFederation/gluu-passport#25]
It will be great if we can clearly tell user through log if user forget to add remote IDP/OP in passport configuration. 

In above scenario, Gluu server is throwing "too many redirects" error which is ambiguous. 

Suggestion from customer: https://support.gluu.org/single-sign-on/5453/too-many-redirects-error-if-passport-request-specifies-a-non-existent-idp/#at33402

**Comment by jgomer2001** [comment]
In newer custom script #38 checks were added. If the remote IDP is not recognized, the user will be bounced to the login page where  manual selection can be done, and the oxauth_script.log will warn about an attempt to use an unknown IDP
