### ISSUE TITLE
Passport social not recognizing any   external identity provider (google, facebook etc ).

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/gluu-passport#291]
### Describe the issue
Passport social not recognize  external identity provider for example google , facebook etc.

### Step to replicate
a) Create google provider under passport  .
b) select type as oauth . stragegy as passport-google-oauth2 and mapping as google.
b) Provide crediential secret and key.
c) Add provider.
d) Set authentication as passport-social.
e) try to login via external provider 

### Expected Result
Its must redirect to external provider for authenticaiton.

### Actual Result.
The selected provider is not recognized as external identity provider is prompt on login screen.

### Screenshot
![Screenshot from 2021-06-08 16-53-50](https://user-images.githubusercontent.com/34593983/121177670-522ac780-c87b-11eb-9fbe-7e78ac9d8a76.png)

### Envrionment.
Ubuntu 20
Gluu Server 4.3.0

**Comment by kdhttps** [comment]
@MohitMaliFtechiz could you please share the `passport.log`, `oxtrust.log` and `oxauth.log`?

**Comment by christian-hawk** [comment]
Hello @MohitMaliFtechiz 

We need more information to replicate. Can you please help me answering:

1. When you say:
>> The selected provider is not recognized as external identity provider is prompt on login screen.

I'm not getting it. When you say "is not recognized", what is showing that? What behavior, log? Who is not recognizing, why?

2. You say version `4.3.0`, that's unreleased. So I assume is a dev build. Do we have a "subversion", a build number, or something like this? If yes, would be nice.

3. Can you provide internal passport version? Please do the following:
```sh
cat /opt/gluu/node/passport/package.json | grep '"version"' 
```

4. Please send:
- `oxauth.log` - TRACE level
- `oxauth_script.log`
- `passport.log` - DEBUG level
- `oxtrust.log` - DEBUG level

Thanks

**Comment by MohitMaliFtechiz** [comment]
Hi @christian-hawk ,

1. "The selected provider is not recognized as external identity provider " this is the error shown on login screen while click on any external identity provider , you can see screenshot attached. 
2.  Yes its early beta release for 4.3.0 , you can get this build [link to build](https://repo.gluu.org/ubuntu/pool/main/focal-devel/gluu-server_4.3.0-100~ubuntu20.04_amd64.deb) .
3.   ``` "version": "4.5.0" ``` is the passport version.
4.  check the attached logs.
[oxauth.log](https://github.com/GluuFederation/gluu-passport/files/6630436/oxauth.log)
[oxauth_script.log](https://github.com/GluuFederation/gluu-passport/files/6630437/oxauth_script.log)
[passport-2021-06-09.log](https://github.com/GluuFederation/gluu-passport/files/6630438/passport-2021-06-09.log)
[passport.log](https://github.com/GluuFederation/gluu-passport/files/6630439/passport.log)

**Comment by christian-hawk** [comment]
thanks @MohitMaliFtechiz will check

**Comment by kdhttps** [comment]
@MohitMaliFtechiz  we fixed this problem, actual problem was in installation and permission. @mbaser  is this fix available on latest setup? if yes then let us know, @MohitMaliFtechiz will test it.

**Comment by kdhttps** [comment]
hello @mbaser , we are still facing permission issue in latest build.
After install i can see this below permissions for passport cert which are  wrong
```

**Comment by mbaser** [comment]
This is fixed with commit https://github.com/GluuFederation/community-edition-setup/commit/67f269c1dccc1a8a7ced817aa5de8e4db895953f

```
# ls -l /etc/certs/passport-*
-r--r----- 1 root gluu 10625 Jul 14 13:08 /etc/certs/passport-rp.jks
-r--r----- 1 root gluu  1712 Jul 14 13:08 /etc/certs/passport-rp.pem
-r--r----- 1 root gluu 10625 Jul 14 13:08 /etc/certs/passport-rs.jks
-r--r----- 1 root gluu  1200 Jul 14 13:08 /etc/certs/passport-sp.crt
-r--r----- 1 root gluu   997 Jul 14 13:08 /etc/certs/passport-sp.csr
-r--r----- 1 root gluu  1679 Jul 14 13:08 /etc/certs/passport-sp.key
-r--r----- 1 root gluu  1751 Jul 14 13:08 /etc/certs/passport-sp.key.orig
```

**Comment by kdhttps** [comment]
Thanks @mbaser , I tested and it is working. There is one bug on oxAuth, created issue here https://github.com/GluuFederation/oxAuth/issues/1552. @MohitMaliFtechiz re-open if you face any problem
