### ISSUE TITLE
Bug: getRPT. Failed to get RPT token in Gluu 4.3.0

### ISSUE THREAD

**Issue by kdhttps** [GluuFederation/gluu-passport#313]
To fetch passport config, we are passing client assertion token to token endpoint with below data:
```
{
  "iss": "1502.83634506-8aaa-4d6d-be23-62bb9fc0ce10",
  "sub": "1502.83634506-8aaa-4d6d-be23-62bb9fc0ce10",
  "aud": "https://ub20.mali.org/oxauth/restv1/token",
  "jti": "67f8c0b5-5360-45cf-8b2a-a316ff40d1c1",
  "exp": 1626863008.771,
  "iat": 1626862978771
}
```

oxAuth is failed to recognised `exp` because it has decimal number `.xxx`.  After rounding number from `1626863008.771` to `1626863008`, oxAuth started accepting it. We need to add this fix.

Currently we are passing decimal number, need to round it, [here](https://github.com/GluuFederation/gluu-passport/blob/master/server/utils/uma.js#L62)

[oxauth.log](https://github.com/GluuFederation/gluu-passport/files/6861029/oxauth.log)
[passport.log](https://github.com/GluuFederation/gluu-passport/files/6861030/passport.log)

**Comment by christian-hawk** [comment]
@kdhttps thanks for the research and fix. @jgomer2001 thanks 4 the help too.

@kdhttps could you please share your thoughts about why it stopped working on `4.3.0-beta`? Was a change in oxauth side?

**Comment by christian-hawk** [comment]
As discussed in internal oxauth channel @yuriyz said he does not know why it was accepting decimals and stopped accepting. 
That being said I'm exceptionally merging this PR without a complete understanding of why it happened.
