### ISSUE TITLE
Make logging level a parameter in config file

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/gluu-passport#32]
Passport uses [winston](https://github.com/winstonjs/winston#logging-levels) for logging. The acceptable level is currently hardcoded at `utils/logger.js` 

We should move this to the config file so users don't have to alter the code to tweak such a common behaviour.

**Comment by natt-tester** [comment]
Agreed, it's added: 
<img width="662" alt="parameter" src="https://user-images.githubusercontent.com/38302725/44251019-383b1880-a23a-11e8-9460-41ef7c3d63d9.png">
