### ISSUE TITLE
`Error in parsing JSON in getJSON` in passport log at startup

### ISSUE THREAD

**Issue by mzico** [GluuFederation/gluu-passport#35]
There is one ERROR log showing at the time of passport service start... which doesn't affect overall services. Do you think we should remove this error message? Or should we modify some json config to remove that error totally? 

Here is the reference comment: https://support.gluu.org/single-sign-on/5451/passport-service-fails-to-start-after-gluu-startup/#at33776

**Comment by jgomer2001** [comment]
Solved as a consequence of fix for #12 and refactoring #33

**Comment by natt-tester** [comment]
I don't see any JSON errors in the log. I believe it's done.
