### ISSUE TITLE
Doc: how to update/add company or org images for External Provider list in Passport login page

### ISSUE THREAD

**Issue by mzico** [GluuFederation/gluu-passport#36]
This is how it looks like now, 

![external_providers](https://user-images.githubusercontent.com/7156097/41053078-44dd8886-6980-11e8-8104-24cf945aff38.png)

We need to prepare a doc how we can replace / update those logo of External Providers

**Comment by jgomer2001** [comment]
related https://github.com/GluuFederation/oxAuth/issues/821 and #34

once we define the "official" way to handle it, we'll document it

**Comment by jgomer2001** [comment]
According to fix for #34 (targetted at 3.1.4), it consists of adding `logo_img` property to the strategy of interest, with value like `../../ext/resources/myimage.jpg` if `myimage.jpg` is copied to `/opt/gluu/jetty/oxauth/custom/static` folder. No need to change anything else

**Comment by jgomer2001** [comment]
absolute url will also work, e.g. https://blah...

`logo_img` was choosen for consistency with respect to saml-based providers (see `/etc/gluu/conf/passport-saml-config.json` for an example)

**Comment by jgomer2001** [comment]
Part of newer docs:
https://github.com/GluuFederation/docs-ce-prod/blob/3.1.4/3.1.4/source/authn-guide/passport.md
