### ISSUE TITLE
Bundle passport with openid connect support

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/gluu-passport#37]
We already have a working [sample](https://gluu.org/docs/ce/authn-guide/inbound-oidc-passport/)

we could make the strategy read parameters like `issuer`, `tokenendpoint`, `userinfoendpoint` from the passport-config (as we already do with clientID, secret)

**Comment by jgomer2001** [comment]
it's key to add to docs how this kind of integration operates and the restrictions the underlying strategy poses

**Comment by willow9886** [comment]
@jgomer2001 are you planning on adding docs for this?
