### ISSUE TITLE
remove rate-limit feat - patch

### ISSUE THREAD

**Issue by kdhttps** [GluuFederation/gluu-passport#383]
In CN setup, users are not able to configure the rate-limit(in production.js). It's causing the bug / production_blocker in some cases. We can not add features "Fetch config from ENVs" in patch release so we decided to remove the rate-limit as a patch.

**Comment by christian-hawk** [comment]
Removing rate-limit Is a breaking change, it changes major. It cannot be back ported. closing.

**Comment by kdhttps** [comment]
Pardon mate! If I did wrong. Let me what to do for patch
