### ISSUE TITLE
logging "dateTime" test is misplaced and has no action trigger

### ISSUE THREAD

**Issue by christian-hawk** [GluuFederation/gluu-passport#387]
```js
    it('should log currect datetime', async () => {
      const passportLogFilePath = path.join(__dirname, '../server/utils/logs/passport.log')
      console.log(passportLogFilePath)
      const logData = await fs.readFile(passportLogFilePath, 'binary')
      const newDate = new Date()
      // YYYY-MM-DD HH
      const currentDateTimeTillHour = `${newDate.getFullYear()}-${('0' + (newDate.getMonth() + 1)).slice(-2)}-${newDate.getDate()} ${newDate.getHours()}`
      assert(logData.includes(currentDateTimeTillHour))
    })
```

This test needs to be rewritten.

If that's the approach:
1. it should be an placed in an integration test, not an unit test
2. `assert.include` should be used, to ensure proper assertion messages from `chai`
3. there should be an action trigger

- [ ] - Backport 4.2.4
- [ ] - Master

**Comment by kdhttps** [comment]
@christian-hawk  Made PRs
Backport 4.2.4: https://github.com/GluuFederation/gluu-passport/pull/388
Master: https://github.com/GluuFederation/gluu-passport/pull/364

> there should be an action trigger

Not getting this point. could you please describe?

**Comment by christian-hawk** [comment]
> @christian-hawk Made PRs Backport 4.2.4: #388 Master: #364
> 
> > there should be an action trigger
> 
> Not getting this point. could you please describe?

Sure. What action is writing `currentDateTimeTillHour` to log?

**Comment by kdhttps** [comment]
ok, mate. There is already an event but add more description in the test. Please check PR here https://github.com/GluuFederation/gluu-passport/pull/364/files

**Comment by kdhttps** [comment]
Done https://github.com/GluuFederation/gluu-passport/pull/364
