### ISSUE TITLE
rename repo to oxPassport

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/gluu-passport#4]
Align the naming convention of this repo with our other software projects.

**Comment by nynymike** [comment]
I think gluu-passport is ok. Passport is not using oxd.

**Comment by willow9886** [comment]
this is about aligning our naming conventions... we have oxTrust, oxAuth, oxd, oxPush, etc. seems appropriate to continue using ox as the handle. Why for this repo only are we using gluu?
