### ISSUE TITLE
Passport github authentication

### ISSUE THREAD

**Issue by mbaser** [GluuFederation/gluu-passport#42]
I got this screen after authenticating by github
![screenshot_2018-08-21_00-56-49](https://user-images.githubusercontent.com/6398752/44369141-03e78680-a4de-11e8-8dca-085b7187070e.png)
Redirect URL is:
https://github.com/login/oauth/authorize?response_type=code&redirect_uri=https%3A%2F%2Fc2.gluu.org%2Fpassport%2Fauth%2Fgithub%2Fcallback&scope=user%3Aemail&client_id=clientID

**Comment by jgomer2001** [comment]
Fixed with this [commit](https://github.com/GluuFederation/oxTrust/commit/e2928070dff35df8ba8d65f64433ab4a7f87a96c) in oxtrust.
