### ISSUE TITLE
Cannot find modules errors when starting passport

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/gluu-passport#43]
Doing QA for 3.1.4 team members have found errors of this nature when starting passport 

`Error: Cannot find module 'passport-dropbox-oauth2'` 

Sometimes with other modules like `passport-openidconnect`, `express`, `winston-daily-rotate-file`, `dateformat`.

They resorted to using `npm install <package-name> –save`

**Comment by jgomer2001** [comment]
This is due to wrong file `/opt/dist/gluu/passport-node_modules.tar.gz` in binary packages

**Comment by syntrydy** [comment]
@jgomer2001  so the packaging team should fix?

**Comment by jgomer2001** [comment]
@syntrydy they should not include that file until this issue is closed. By default, if the file is missing, the installer does the standard npm installation that requires internet connectivity

**Comment by jgomer2001** [comment]
the .tar.gz looks proper now. I'll reopen if there are problems in QA for release candidate packages
