### ISSUE TITLE
HTTP ERROR 404 on /oxauth/postlogin

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/gluu-passport#45]
1. Enable passport social following [this ](https://gluu.org/docs/ce/3.1.4/authn-guide/passport/) documentation
2. Login with external provider (I verified with google and github)
After providing valid credential, User is getting redirected to {Gluu}/oxauth/postlogin and giving 404

![image](https://user-images.githubusercontent.com/21104811/45482922-f5069380-b76c-11e8-915c-9af950ab9d84.png)

**Comment by jgomer2001** [comment]
@sahiliamsso can you let me know if other authn methods work in that host? for instance try u2f

**Comment by sahiliamsso** [comment]
u2f is also not working

**Comment by jgomer2001** [comment]
probably not, it has to do with this issue https://github.com/GluuFederation/oxauth/issues/898

not all relevant occurrences were changed

**Comment by jgomer2001** [comment]
I'll update all those related to cust scripts (which includes passport), but will have to wait for a new build

**Comment by sahiliamsso** [comment]
It was fixed in RC5
