### ISSUE TITLE
Add logging transport for stdout

### ISSUE THREAD

**Issue by iromli** [GluuFederation/gluu-passport#47]
In docker environment, it's easier to check logs via `stdout`. This is an example on how we _patch_ `logger.js` to use `console` instead of `rotated file`: https://github.com/GluuFederation/docker-oxPassport/blob/0129ae05059e71f87063c936418f9aff903a4f35/logger.js#L38.

One of the reasons why we prefer `stdout` is because we want to utilize external tools such as fluentd, logstash, filebeat, etc, to retrieve logs and transport them to another backend.

We would like to see built-in support for `stdout` transport for our usecase.

**Comment by jgomer2001** [comment]
@iromli I added a [property](https://github.com/GluuFederation/community-edition-setup/commit/7e3d75de9dcc3faf4528c23af051b6b6d5275545) to `passport-config.json` so log output is redirected to console only. Use `"consoleLogOnly" : true`
