### ISSUE TITLE
Passport Log Should Read "passport.log" and archive as "passport-$DATE.log"

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/gluu-passport#48]
Currently Passport will log in this format `passport-$DATE.log`, e.g `passport-2018-10-06.log`, and there is no central location for current logs, as is standard with oxAuth (oxauth.log), oxTrust (oxtrust.log), etc. Passport should be logged as `passport.log` and archived as `passport-$DATE.log` for ease of operations going forward.

**Comment by natt-tester** [comment]
Tested in 3.1.5_5: it's DONE:
<img width="462" alt="passport_log" src="https://user-images.githubusercontent.com/38302725/50375235-96b64000-05fa-11e9-9fd4-d418768cbd60.png">
