### ISSUE TITLE
Support SAML response encryption

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-passport#5]
Some IDP's may want to encrypt the response. If this is the case, Passport will have to generate a private key, and share the corresponding public key with the IDP. It would be ok if passport uses the same private key and public key for all inbound SAML transactions. Perhaps these should be generated automatically when `setup.py` is run. Passport should **not** use a keypair generated for a different service.

[Passport-saml](https://github.com/bergie/passport-saml) already defines  `decryptionPvk` and `decryptionCert`

*NOTE*: We do not want to encrypt the request. There is no point spoofing a request, because the response is always sent to the pre-registered callback URL.

**Comment by arvindsinghtomar** [comment]
> Perhaps these should be generated automatically when setup.py is run. Passport should not use a keypair generated for a different service

@nynymike  I have updated setup.py from next version of gluu we will have separate certificates to use with passport-inbound-saml .
I have generated passport-sp.cer and passport-sp.key from setup.py to use with `decryptionPvk` and `decryptionCert`.  

pr :-https://github.com/GluuFederation/community-edition-setup/pull/370/commits/ed1918a915dfece5a48faa4dc7acb075f9746cbc
