### ISSUE TITLE
Passport service doesn't perform restart properly / Error: Received unexpected HTTP status code of 503

### ISSUE THREAD

**Issue by mzico** [GluuFederation/gluu-passport#51]
Installed passport in 3.1.4. By default it's running as I said 'yes' at the time of installation. 
I added my external IDP in saml config file and went to stop/start passport; but passport didn't start. 
I had to remove passport related logs manually to start passport again. 
Whole output from terminal is below: 

```
- Ubuntu 16.04
- Gluu Server version: 3.1.4

root@localhost:/etc/gluu/conf# service passport stop
Stopping passport: OK
root@localhost:/etc/gluu/conf# service passport start
Starting passport:
Checking logs for possible errors:
Some error encountered...
See log below: 

2018-10-21T19:11:46+0000 [WARN] Error: Received unexpected HTTP status code of 503
2018-10-21T19:12:46+0000 [WARN] Error: Received unexpected HTTP status code of 503
2018-10-21T19:13:46+0000 [WARN] Error: Received unexpected HTTP status code of 503
2018-10-21T19:14:29+0000 [WARN] Error: Received unexpected HTTP status code of 503

For details please check /opt/gluu/node/passport/server/logs/passport-2018-10-21.log .

Stopping passport: OK

Exiting...
root@localhost:/etc/gluu/conf# rm -f -r /opt/gluu/node/passport/server/logs/
.audit.json              passport-2018-10-21.log  start.log                
root@localhost:/etc/gluu/conf# rm -f -r /opt/gluu/node/passport/server/logs/*
root@localhost:/etc/gluu/conf# ls /opt/gluu/node/passport/server/logs/
root@localhost:/etc/gluu/conf# service passport start
Starting passport:
Checking logs for possible errors:
PID: [18321]
OK Sun Oct 21 19:15:53 UTC 2018
root@localhost:/etc/gluu/conf# service passport status
Node running pid=18321

NODE_HOME     =  /opt/node
NODE_BASE     =  /opt/gluu/node/passport/server
NODE_CONF     =  
NODE_PID_FILE      =  /var/run/passport.pid
NODE_START    =  /opt/gluu/node/passport/server/app.js
NODE_LOGS     =  /opt/gluu/node/passport/server/logs
NODE_STATE    =  /opt/gluu/node/passport/server/passport.state
CLASSPATH      =  
NODE           =  /opt/node/bin/node
NODE_OPTIONS   =  PORT=8090 NODE_ENV=unknown NODE_CONFIG_DIR=/opt/gluu/node/passport/server HOSTNAME=localhost NODE_LOGGING_DIR=/opt/gluu/node/passport/server/logs
NODE_ARGS     =  --max-old-space-size=384
RUN_CMD        =  PORT=8090 NODE_ENV=unknown NODE_CONFIG_DIR=/opt/gluu/node/passport/server HOSTNAME=localhost NODE_LOGGING_DIR=/opt/gluu/node/passport/server/logs /opt/node/bin/node --max-old-space-size=384 /opt/gluu/node/passport/server/app.js

root@localhost:/etc/gluu/conf# 

```

**Comment by yurem** [comment]
On which server we can find logs?
```
For details please check /opt/gluu/node/passport/server/logs/passport-2018-10-21.log
```

**Comment by jgomer2001** [comment]
also see https://github.com/GluuFederation/gluu-passport/issues/49#issuecomment-437669058

**Comment by jgomer2001** [comment]
> I added my external IDP in saml config file and went to stop/start passport; but passport didn't start.

@mzico there is no need to apply restarts after configuration changes in 3.1.4 onwards. Waiting 1 min suffices

**Comment by jgomer2001** [comment]
@ganesh-at-wiw starting with passport 3.1.4 there is no need to check log for errors at startup

Due to passport dependency on oxauth and oxtrust, and that most of times these applications are not ready when passport is starting, we added a mechanism in node application to retry until data is available. In that sense, there might be errors in log but they disappear once passport is enabled, configured and oxtrust is ready.

This also helped us avoid the need of doing frequent manual restarts

**Comment by ganesh-at-wiw** [comment]
Hello @jgomer2001 if that is the case that we don't need to check log for errors at startup, should we assume that the service will be started automatically?
If that is the case, we can remove the dependability in next commit, else below is the fix for now.

https://github.com/GluuFederation/community-edition-setup/commit/1645f9f7c49f61169c41a6e6d89813369c089e7a#diff-34b91de3b6cf5b1fad78ef4a6b245b09

**Comment by jgomer2001** [comment]
>  should we assume that the service will be started automatically

yes

**Comment by ganesh-at-wiw** [comment]
That's cool.
Then I think we can close this issue.

**Comment by natt-tester** [comment]
Passport still doesn't start properly in 3.1.5_3 and when you try to (re)start it manually, there are errors in the logs:
[start.log](https://github.com/GluuFederation/gluu-passport/files/2692001/start.log)

**Comment by mbaser** [comment]
this commit closed this issue: https://github.com/GluuFederation/community-edition-setup/commit/e7bcc464b31821ec0ad8fa81b5eeb0b5ca7ba724

 @natt-tester please download this setup.py, and then install: https://github.com/GluuFederation/community-edition-setup/edit/version_3.1.5/setup.py

@natt-tester  Please close this issue after confirmation.

**Comment by jgomer2001** [comment]
seems fine in 3.1.5-4

**Comment by natt-tester** [comment]
Tested in 3.1.5-5, it's DONE.
