### ISSUE TITLE
Enhance IDP-initiated inbound flow

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/gluu-passport#56]
According to internal team discussions, IDP-initiated needs different kind of adjustments. For instance:

1. Honor relaystate param
1. Use an oxauth's custom authz req param instead of state to pass profile
1. Allow different final redirect URLs

**Comment by jgomer2001** [comment]
Point 2 was not solved, so still using `state`

**Comment by shmorri** [comment]
Documented [here](https://gluu.org/docs/ce/4.0/authn-guide/inbound-saml-passport/#idp-initiated-inbound-flow)
