### ISSUE TITLE
Can't add second Google OpenID passport strategy

### ISSUE THREAD

**Issue by dgoings** [GluuFederation/gluu-passport#57]
## General description

I'd like to be able to configure inbound OpenId authentication via Google for two separate google domains. I have created applications and obtained clientIds and secrets for both domains. I have passport setup and working. I can add the first google domain under the regular "google" passport strategy, but I can't add a second one with the same strategy name, so I have tried to follow the steps under the "Supporting a new strategy" docs here: https://gluu.org/docs/ce/authn-guide/passport/#supporting-a-new-strategy. But when I add the new strategy in oxTrust, the passport server fails to run and doesn't provide any logging as to why.

### Expected Behavior
I can add a second custom passport strategy for a Google app.

### Actual Behavior
Adding the new strategy causes the passport server to fail to run.

### Steps to reproduce
1. Copy the `google.js` file under `/opt/gluu/node/passport/server/auth` to a new file named `groundspeed.js`.
2. Edit `groundspeed.js` so that the `callbackURL` points to a custom url setup in the Google client app (e.g. `/passport/auth/groundspeed/callback`).
3. Edit `configureStrategies.js` to import `groundspeed.js` and check for `data.passportStrategies.groundspeed` (copy the check for Google and update names accordingly)
4. Edit `/opt/gluu/node/passport/server/routes/index.js` to import `groundspeed.js` and add sections to handle the new app callback:
```
//===================== groundspeed =================
router.get('/auth/groundspeed/callback',
    passportGroundspeed.authenticate('google', {
        failureRedirect: '/passport/login'
    }),
    callbackResponse);

router.get('/auth/groundspeed/:token',
    validateToken,
    passportGroundspeed.authenticate('google', {
        scope: ['profile', 'email']
    }));
```
6. At this point, everything should still be working. Now add the new strategy to oxTrust under `Manage Authentication > Passport Authentication Method`. Name the strategy "groundspeed" and enter the client id and secret.
7. At this point, passport should automatically pick up the changes, but it doesn't. If you stop the passport server and try to start it again, it exits but without giving any errors, and `passport.log` doesn't show an error.

<img width="616" alt="Strategy shows up in oxTrust" src="https://user-images.githubusercontent.com/621865/52591765-b572cf00-2e12-11e9-8bea-dbfe3e2e6151.png">
<img width="1046" alt="Logs show new strategy read in successfully" src="https://user-images.githubusercontent.com/621865/52591770-b9065600-2e12-11e9-8949-e3e418e13c06.png">
<img width="1195" alt="Passport server won't start and no error" src="https://user-images.githubusercontent.com/621865/52591775-bad01980-2e12-11e9-9df7-e63b568ea33f.png">

**Comment by dgoings** [comment]
Gluu Support forum ticket: https://support.gluu.org/authentication/6653/cant-add-second-google-openid-passport-strategy/

**Comment by jgomer2001** [comment]
I'm closing this because according to ticket, passport is not the fit for the problem at hand.
