### ISSUE TITLE
Support auto renewal of SAML certificates

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/gluu-passport#59]
We have to consider adding support for the need described in [this](https://support.gluu.org/6717/#at46654) support ticket.

Currently both SP and IDP have to stop and manually reconfigure with the renewed cert.

**Comment by christian-hawk** [comment]
This issue will be implemented in inbound-saml issue #32:  https://github.com/GluuFederation/inbound-saml/issues/32
