### ISSUE TITLE
Support other SAML params

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/gluu-passport#6]
[Passport-SAML](https://github.com/bergie/passport-saml) supports a few useful options, for example, `forceAuthn` or `identifierFormat`. Is there a way to ad hoc configure extra options?

**Comment by arvindsinghtomar** [comment]
Currently, we have not added all the param, But we will map other optional params, too. so users will be able to map extra options as well.

**Comment by arvindsinghtomar** [comment]
@nynymike  I have added few extra options like forceAuthn,identifierFormat ,requestIdExpirationPeriodMs ...
user can use these params(options) by putting it into passport-saml-confing.json like wise other params.
commit - af1112e7197e60d74e26adec363024029a1ccfcb

**Comment by arvindsinghtomar** [comment]
@nynymike  
i have  added forceAuthn param to passport-inbound but currently gluu server is not supporting that param I confirm from @Dimitry, 
It is going to resolved in next version of gluu 3.1.2

**Comment by nynymike** [comment]
What does passport have to do with Shibboleth? Please explain.
