### ISSUE TITLE
Add a cache provider when inResponseTo validation is used in a clustered environment

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/gluu-passport#60]
As described [here](https://github.com/bergie/passport-saml/#cache-provider) `inResponseTo` validation can fail when used in a multiple server scenario.

We can add a custom memory cache provider using the same redis server shared by all cluster nodes so validation does not fail.

**Comment by shmorri** [comment]
Documented [here](https://gluu.org/docs/ce/4.0/authn-guide/inbound-saml-passport/#cache-provider-configuration)
