### ISSUE TITLE
Verify linkedIn integration is working properly

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/gluu-passport#62]
A community member raised this [support ticket](https://support.gluu.org/7156/) reporting a problem with LinkedIn integration: *This resource is no longer available under v1 APIs*

the linkedin lib bundled with Gluu already uses the v2 urls, but still we need to validate and adjust if needed. 

@sahiliamsso can you validate if this is hapenning in the 4.0 tests you are doing?

**Comment by jgomer2001** [comment]
Also check the deprecation problem reported in this [ticket](https://support.gluu.org/single-sign-on/7160/windowslive-passport-strategy-not-working/)

**Comment by sahiliamsso** [comment]
It is reproducible in latest 4.0

2019-06-19T22:58:40.688Z [ERROR]    Unknown Error: InternalOAuthError: failed to fetch user profile (status: 410 data: {
  "errorCode": 0,
  "message": "This resource is no longer available under v1 APIs",
  "requestId": "T0931U9JX8",
  "status": 410,
  "timestamp": 1560985120664
})

**Comment by jgomer2001** [comment]
It's due to changes in LinkedIn API and auht0's passport-linkedin-oauth2 apparently not being maintained 

Some pointers:
https://github.com/auth0/passport-linkedin-oauth2/issues/77
https://github.com/auth0/passport-linkedin-oauth2/issues/75
https://github.com/auth0/passport-linkedin-oauth2/pull/63

Checking if we can use this strategy now:
https://github.com/sokratisvidros/passport-linkedin-oauth2/

**Comment by jgomer2001** [comment]
I tested and we can use sokratisvidros repo

I'm awaiting input from https://github.com/SokratisVidros/passport-linkedin-oauth2/issues/2 and will proceed
