### ISSUE TITLE
Encrypt profile data

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/gluu-passport#73]
User profile is sent from passport to oxauth in JWT form. In the case of idp-initiated flow, data is passed in the URL as param state.

We can encrypt this info to avoid exposing data: needs encryption in node code plus decryption in custom script

**Comment by nynymike** [comment]
Is it possible to send via POST so that we can use TLS encryption?

**Comment by jgomer2001** [comment]
In the end the state param (even custom params) will be appended to the redirect_uri as response to the authentication request, so they are visible again.

The problem stems from the fact that the SAML assertion (profile data) is sent straight to passport ACS  at a point where there is no existing OIDC authz request in Gluu, so passport help us create one (in which the profile stuff is contained)

**Comment by yurem** [comment]
I think we need to review all AuthZ parameters resend in URL on transition between `authorize` endpoint <-> `/authorize.htm`. For me we need to remove them because we already store them in session. And as result it will reduce changes to modify or view them in browser URL.
