### ISSUE TITLE
Implement cache for inresponsevalidation based on memcached

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/gluu-passport#79]
Currently 2 options are offered: in-memory (suitable for single node only) and redis, let's add memcached.

**Comment by nynymike** [comment]
Why do we need memcached? Is it for CB support?

**Comment by yurem** [comment]
Can we use https://github.com/expressjs/session store? Please scroll down to `Compatible Session Stores`. It supports all caches which we need or used.

**Comment by jgomer2001** [comment]
It's an interesting idea, however I think it is not technically feasible due passport-saml design: the cache handler instance is passed upon strategy instantiation, eg:

```
passport.use(new SamlStrategy({
  	...
  	cacheProvider: ...
  	...
  }
```

so there is no access to `req.session` at this point. Also the [methods](https://github.com/bergie/passport-saml/#cache-provider) this object has to implement do not receive `req` unfortunately.

By now, passport 4.1 has redis & memcached support. We can revisit this topic in 4.2 because we'll need to use those session stores to be able to run passport on multi node setups.

**Comment by jgomer2001** [comment]
Superseded by #83
