### ISSUE TITLE
Implement LDAP persistent express session store

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/gluu-passport#82]
Currently passport employs [this](https://www.npmjs.com/package/memorystore) session store. We need to create one that can use the underlying Gluu LDAP.

Relevant pointers:

- https://github.com/expressjs/session
- https://gluu.org/docs/ce/4.1/reference/persistence/
- http://ldapjs.org/client.html
- https://github.com/GluuFederation/oxCore/blob/version_4.1.0/persistence-ldap-sample/src/main/java/org/gluu/ldap/LdapSampleEntryManager.java

The session store has to save objects under branch `ou=cache,o=branch`. [Here](https://github.com/GluuFederation/community-edition-setup/blob/version_4.1.0/schema/gluu_schema.json#L5867-L5885) is the LDAP schema of an entry. 

To better understand, install Gluu server with defaults and configure it to use native persistence as [cache provider](https://gluu.org/docs/ce/4.1/reference/cache-provider-prop/). Then [connect](https://gluu.org/docs/ce/user-management/local-user-management/#manage-data-in-gluu-ldap) to LDAP using a graphical client and inspect the branch mentioned.

This [java bean](
https://github.com/GluuFederation/oxCore/blob/version_4.1.0/core-cache/src/main/java/org/gluu/service/cache/NativePersistenceCacheEntity.java) is self explanatory of what those short LDAP attributes mean.

I think we may create a small separate repo for this task and then reuse it as a library in passport because we need to plug other stores as described in #81, depending on the underlying Gluu CE configuration. The library should just take the parameters relevant to establish the connection to LDAP.

**Comment by nynymike** [comment]
It's important to remember that we need to support both LDAP and Couchbase. So we should make sure that the session store defines a high level interface, and then we can add implemenation and tests for both LDAP and Couchbase.

**Comment by jgomer2001** [comment]
The high level definition [already exists](https://github.com/expressjs/session#session-store-implementation) as well as the other required [stores](https://github.com/expressjs/session#compatible-session-stores) (see #81)

**Comment by jgomer2001** [comment]
Superseded by #83
