### ISSUE TITLE
IDP-initiated: postlogin.xhtml not calling script's authenticate

### ISSUE THREAD

**Issue by yurem** [GluuFederation/gluu-passport#95]
state parameter incorrectly handled by JSF2 during redirect from `authorize` to `authorize.htm`. There is workarounds. We can replace . with _ in JWT encoded string.
@christian-hawk has testing environment where we can reproduce this bug

**Comment by yurem** [comment]
There is similar issue between Rest and Spring: https://stackoverflow.com/questions/16332092/spring-mvc-pathvariable-with-dot-is-getting-truncated

But in our case Rest resend sate parameter correctly. Hence in our case it's related to JSF2 only

**Comment by christian-hawk** [comment]
@yurem JWT correctly parsed is being sent, but when it enters on SamlPassportAuthenticator.py getpageforstep, after returning `/postlogin.xhtml` we have the same problem then before...

Before that happen, we have in `isInboundFlow()`, (`if`) `sessionId = None` and never reaches the (`else`) `authz_state = identity.getSessionId().getSessionAttributes().get(AuthorizeRequestParam.STATE)`

So looks like is something regarding session id. Maybe you can help?

I also found this: https://github.com/GluuFederation/oxAuth/commit/031a3d15ea985505c95fee73196f0d7e7ab2449b
It's a recent commit about session endpoint, that uses the method used by the JSF. Just in case it helps, it's the only change in this function for a long time

You can loggin in my test env if you want it's up and running

**Comment by christian-hawk** [comment]
Attaching logs @yurem 

[merged_logs.log](https://github.com/GluuFederation/gluu-passport/files/4897582/merged_logs.log)
[har.log](https://github.com/GluuFederation/gluu-passport/files/4897604/har.log)
